import React from 'react';
import Head from 'next/head'
import Header from '../component/Header/Header'
import Container from '@mui/material/Container';
import {CartProvider} from './context/CartContext'
import Footer from './Footer';

function Layout({children}) {
    return(
        <div>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <CartProvider>
            <Header />
            <main style={{minHeight: 'calc(100vh - 192px)'}}>
                <Container style={{marginTop: '100px'}}>
                    {children}
                </Container>
            </main>
            <Footer />
        </CartProvider>
        </div>
    )
}
export default Layout;